playstudio_project:
  outputs:
    prod:
      dbname: warehouse_db
      host: postgres
      pass: airflow
      port: 5432
      schema: silver_layer
      threads: 1
      type: postgres
      user: airflow
    dev:
      dbname: warehouse_db
      host: localhost
      pass: airflow
      port: 5432
      schema: silver_layer
      threads: 1
      type: postgres
      user: airflow
  target: dev

        # pass: airflow

